[package]
name = "problem"
version = "0.1.0"
edition = "2021"

[lints.rust]
dead_code = "allow"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
